### ISSUE TITLE
iOS Implementation file has lots of errors

### ISSUE THREAD

**Issue by ShahriatHossain** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#19]
iOS Implementation file has lots of errors that has been modified 6 days ago. Do you have stable version for it because in earlier version was getting filename null?

**Comment by jfversluis** [comment]
That would be my bad! I will try to look into it today

**Comment by jfversluis** [comment]
Source is updated now and should build again. Although if you are using the NuGet, the code is still the same. We still have to package this new source to a new version on NuGet.
