### ISSUE TITLE
iOS system exception "You should reference the NuGet package"

### ISSUE THREAD

**Issue by riandesign** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#28]
I installed the NuGet in PCL and iOS and also configurated the iCloud Kit on developer.apple, but I got this error:

`System.Exception: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.`

**Comment by Proyoyo** [comment]
You need to link the iOS dll files from your iOS project. To find the required dll, go to the NuGet package -> lib -> MonoTouch10 -> select the 2 dll files there & add it to your iOS project reference.

**Comment by jfversluis** [comment]
I shouldn't reference it like that, you should install it as a NuGet also on your iOS project.

**Comment by riandesign** [comment]
But the problem is the NuGet is outdated and it doesn't work on iOS at all.

**Comment by jfversluis** [comment]
@riandesign I will look into it, please try not to go through every issue and report the error you have. Once is enough. I will try to find some time tomorrow to have a look.

**Comment by Jamarsoft** [comment]
I am having the exact same issue with the nuget.  Did this ever get fixed and if so how?

**Comment by GlenConway** [comment]
I'm having the same issue with an iOS project. Don't understand why this issue is closed if it's still a problem.

**Comment by Char0394** [comment]
I'm having the same issue!  Any news about it?

**Comment by ahmedelashkerpersonal** [comment]
Same issue

**Comment by caiorios** [comment]
I am facing the same issue. Any clean solution?

**Comment by sravanthiakula** [comment]
Me too have the same issue? An update on it?

**Comment by CarLoOSX** [comment]
same problem

**Comment by CarLoOSX** [comment]
tested in a blank project

**Comment by jfversluis** [comment]
@CarLoOSX this is fixed on the fork of this in my repo and accompanied NuGet. 

In an effort to further develop this plugin I have moved it into my own account: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows.

Please look for the pre-release package.
