### ISSUE TITLE
NotImplementedException in iOS

### ISSUE THREAD

**Issue by zipgenius** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#3]
Hello.
I'm trying to use your package for iOS development.
I called:
`var ss = CrossFilePicker.Current;`

But I got a System.NotImplementedException.
Am I using it right? What's the correct way to use CrossFilePicker?

**Comment by drmolfar** [comment]
Same issue on iOS.
Android and UWP works fine.
Checked both 1.1.0 and 1.0.0 versions.

**Comment by zl1ji** [comment]
I am having the same issue, notice that the Nuget package added to my iOS project is a PCL one. 

I think this is the cause of the problem, but don't know how to solve it beside trying to compile the FilePicker and import assemblies myself instead of using Nuget.

**Comment by drmolfar** [comment]
Yes, importing assemblies manually solve the problem.

**Comment by sreekanthbantu** [comment]
Issue was solved by importing dll's but not getting 'file name', showing null.

**Comment by MarkFred** [comment]
I'm having the same problem. This is my first time with xamarin.
I understand i need to import the ios assembly manually.

can somebody please tell me how:
1. to get the assembly for ios?
2. to import i manually?

Thanks in advance!

**Comment by markobls** [comment]
Thanks @Mark-van-Dijk 
I had the same problem and your answear helped me.
Ty

**Comment by jfversluis** [comment]
Not sure what the status of this issue is. Could you please open a new one if this is still happening?
