### ISSUE TITLE
Error getting value from 'DataArray'

### ISSUE THREAD

**Issue by riandesign** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#30]
I tested it on iOS and I got this error:
`System.Exception: Error getting value from 'DataArray' on 'Plugin.FilePicker.Abstractions.FileData'.`

My code:
```
try {
     FileData filedata = await CrossFilePicker.Current.PickFile();
} catch (Exception ex) {
     throw new Exception(ex.Message);
}
```

**Comment by elmernocon** [comment]
@riandesign , Hi it seems this is caused by line 71 in [FilePickerImplementation.cs](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.iOS/FilePickerImplementation.cs).

Changing it to `OnFilePicked (new FilePickerEventArgs (dataBytes, filename, pathname));` should fix it, because line 141 in [FilePickerImplementation.cs](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.iOS/FilePickerImplementation.cs) expects a FilePath.

@jfversluis any thoughts?

**Comment by riandesign** [comment]
@elmernocon , but I don't have the variable `pathname`. Thus, it doesn't exist in the context.
What shoul I do in this case?

**Comment by elmernocon** [comment]
@riandesign , this should do the trick.
```
string filename = doc.LocalizedName;
string pathname = doc.FileUrl?.ToString();

// iCloud drive can return null for LocalizedName.
if (filename == null)
{
     // Retrieve actual filename by taking the last entry after / in FileURL.
     // e.g. /path/to/file.ext -> file.ext

     // filesplit is either:
     // 0 (pathname is null, or last / is at position 0)
     // -1 (no / in pathname)
     // positive int (last occurence of / in string)
     var filesplit = pathname?.LastIndexOf ('/') ?? 0;

     filename = pathname?.Substring (filesplit + 1);
}
```

**Comment by jfversluis** [comment]
@elmernocon great work! If you could pour this into an PR I will check it out somewhere today or tomorrow and if it looks good, I can merge it in.

**Comment by riandesign** [comment]
@elmernocon @jfversluis I still got the same error:
`System.Exception: Error getting value from 'DataArray' on 'Plugin.FilePicker.Abstractions.FileData'.`

**Comment by elmernocon** [comment]
@riandesign , hmm, did you recompile?

**Comment by riandesign** [comment]
@elmernocon, yes. I rebuild the DLLs.

**Comment by riandesign** [comment]
@elmernocon any idea?

**Comment by riandesign** [comment]
@elmernocon @jfversluis I realized the problem is not with FilePath. I tried the code below and I still got the same error:

```
if (e != null && e.FilePath != null)
    tcs.SetResult(new FileData(e.FilePath, e.FileName, () => File.OpenRead(e.FilePath)));
else
    tcs.SetResult(null);
```

**Comment by riandesign** [comment]
@elmernocon @jfversluis any idea?

**Comment by elmernocon** [comment]
@riandesign , Hi, can you try these changes?

In the class [FileData](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.Abstractions/FileData.cs)

1. Add the field: `private byte[] _dataArray = null;`
2. Change the property 'DataArray' GET to:
```
public byte[] DataArray
{
     get { return _dataArray; }
}
```
3. Add/replace a/the new/existing constructor with:
```
public FileData (byte[] dataArray, string fileName, string filePath)
{
     _dataArray = dataArray;
     _fileName = fileName;
     _filePath = filePath;
}
```
4. Optional: You can get rid of the members related to _streamGetter or _dispose.

the reasoning for this is we're already getting and passing the dataArray (byte[]) but it's not being used. see:
- [FilePickerEventArgs](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.Abstractions/FilePickerEventArgs.cs) line 29: `public FilePickerEventArgs (byte [] fileByte, string fileName, string filePath) : this (fileByte, fileName) { ... }`
- [FilePickerActivity (Android)](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.Android/FilePickerActivity.cs) line 58: `OnFilePicked (new FilePickerEventArgs (file, fileName, filePath));`
- [FilePickerImplementation (iOS)](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.iOS/FilePickerImplementation.cs) line 71: `OnFilePicked (new FilePickerEventArgs (dataBytes, filename, pathname));`

- [FilePickerImplementation (Android)](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.Android/FilePickerImplementation.cs) line 59: `tcs?.SetResult (new FileData (e.FilePath, e.FileName, () => System.IO.File.OpenRead (e.FilePath)));`
- [FilePickerImplementation (iOS)](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.iOS/FilePickerImplementation.cs) line 141: `tcs?.SetResult (new FileData (e.FilePath, e.FileName, () => File.OpenRead (e.FilePath)));`

so now with the changes to FileData replace the following lines with:
- [FilePickerImplementation (Android)](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.Android/FilePickerImplementation.cs) line 59: `tcs?.SetResult (new FileData (e.DataArray, e.FileName, e.FilePath));`
- [FilePickerImplementation (iOS)](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.iOS/FilePickerImplementation.cs) line 141: `tcs?.SetResult (new FileData (e.DataArray, e.FileName, e.FilePath));`

@jfversluis any thoughts?

**Comment by riandesign** [comment]
@elmernocon I can't do this: [FilePickerImplementation](https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/blob/master/FilePicker/FilePicker/Plugin.FilePicker.iOS/FilePickerImplementation.cs) (iOS) line 141: tcs?.SetResult (new FileData (e.DataArray, e.FileName, e.FilePath));

Because FilePickerEventArgs doesn't have e.DataArray.

**Comment by elmernocon** [comment]
@riandesign Hi, yeah missed that on my part, fixed the comment above :)

Quick question, were you able to make the document picker appear on an iPad Simulator / iPad?

**Comment by riandesign** [comment]
@elmernocon I haven't test on Simulator. I've tested it on iPhone device.

**Comment by elmernocon** [comment]
@riandesign if possible can you test it on an iPad Simulator?

**Comment by msarun006** [comment]
` private async void btnUpload_Clicked(object sender, EventArgs e)
        {
            FileData fileData = await CrossFilePicker.Current.PickFile();
            Byte[] byteArray = fileData.DataArray;                              // when i select pdf  or doc from GoogleDrive Its getting DataArray = empty;//
            await CrossFilePicker.Current.SaveFile(fileData);
            if (fileData.FileName == string.Empty)
            {
                string filepath1 = await DependencyService.Get<ISaveFile>().SaveFiles("uploadedfile.pdf", byteArray);
                await DisplayAlert("Downloaded File path", filepath1, "ok");
               
            }
            else
            {
                string fileName = fileData.FileName;
                string filepath = await DependencyService.Get<ISaveFile>().SaveFiles(fileName, byteArray);
                await DisplayAlert("Downloaded File path", filepath, "ok");
                var fstream = new MemoryStream(byteArray);
                imgSelected.Source = ImageSource.FromStream(() => fstream);
            }
         
          
        }`




>  when i select pdf  or doc from GoogleDrive Its getting DataArray = empty;//

**Comment by divvugarimella** [comment]
hi just add
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" /> in your manifest file
@divya morampudi

**Comment by divvugarimella** [comment]
hi just add
 permissions in your
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
in  manifest file and 
 public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        } in mainactivity.cs

@divya morampudi
