### ISSUE TITLE
When I try to upload pdf file size is showing me {byte[0]}

### ISSUE THREAD

**Issue by ShahriatHossain** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#36]
I am trying to upload pdf from my android 5.1 device but getting media object like below:

{byte[0]}

"sample.pdf"

"/document/acc=1;doc=14"

can anybody help me whats wrong here? Why pdf is not uploading and file size is 0?

**Comment by salvador-guerrero** [comment]
This seems to happen when you pick a file from Google Drive

**Comment by ShahriatHossain** [comment]
@salvador-guerrero no this also happens when try to pick file from download redirectory on android some devices like 5.1 and 6.1 etc. Do you have any solution for this type of problems?

**Comment by mhallmark** [comment]
This is happening for us as well. DataArray coming back as empty byte array when selecting from google drive and one drive accounts. The file name is correct though.

Samsung Note 5 on API 23 and Google Nexus on API 24.

**Comment by ShahriatHossain** [comment]
@mhallmark so have you found any solution? Because when I choose file from downloads this is also happening.

**Comment by mhallmark** [comment]
@ShahriatHossain Unfortunately, no.

**Comment by gabybonaventura** [comment]
I had had the same problem and i finally solved it using a beta version of FilePicker (Version 2.0.64-beta).

**Comment by jfversluis** [comment]
Yes, please use the package that is forked from here and actively maintained here: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows

**Comment by akoh-victor** [comment]
@gabybonaventura Please iam having an issue using 2.0.64-beta i installed the package from the package manager but my xamarin forms app is not seeing that its install

**Comment by gabybonaventura** [comment]
@ideal-it-solutions 
you installed the package on plc project, ios project and android project?
If the answer is yes, Try to rebuild all project and restart your visual studio

**Comment by akoh-victor** [comment]
@gabybonaventura yes i install to Android project and  IOS project. 
![android](https://user-images.githubusercontent.com/16347216/38556143-8b75edd4-3cc0-11e8-8f57-0f58972b3ffd.PNG)

 after installing to both ios and android project.
restarted and rebuild my project 
tried to reference it like this 
![capture](https://user-images.githubusercontent.com/16347216/38549176-6010fb94-3cab-11e8-9909-43f693826bd0.PNG)
and this
![capture 2](https://user-images.githubusercontent.com/16347216/38549243-838d6e4a-3cab-11e8-8d9e-55b16c563093.PNG)

**Comment by gabybonaventura** [comment]
@ideal-it-solutions
Try to include the package with Manage NuGet Package, Search Xamarin.Plugin.FilePicker and include prerelease.
Your project is make with Xamarin Forms?

**Comment by jfversluis** [comment]
If you have any issues with the NuGet package from the repo above, please open an issue there. I won't be going into specifics here.

**Comment by akoh-victor** [comment]
@gabybonaventura  Thank you, that worked for me.
