### ISSUE TITLE
External storage read and write permission is not handled by plugin itself for sdk 23 or later in android

### ISSUE THREAD

**Issue by ShahriatHossain** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#39]
Hi,
When I try to upload pdf file the file size is coming 0 and this is happening for android sdk>=23 because I have already set permission for read and write external storage in my Menifest file but for sdk >=23 it needs to handle it manually to get permission from user. And I think this plugin doesn't handle it from itself. Can anybody suggest me what should I do now?

**Comment by ShahriatHossain** [comment]
@jfversluis can you suggest the better approach to solve this problem.

**Comment by jfversluis** [comment]
There is a [permissions plugin](https://github.com/jamesmontemagno/PermissionsPlugin) by James Montemagno, maybe you can use that to get permission from within the app?

**Comment by ShahriatHossain** [comment]
@jfversluis  I have already used that plugin that only works for android 6 and later but I can see that my other android devices like 5.1 and 6.0.1 and some Motorola E model devices are not working and getting only file size 0 when trying to browse pdf files from Download location. Not sure why this is happening.

**Comment by jcus0006** [comment]
Call the below method in the OnCreate() method of the MainActivity class.

```
private void CheckAppPermissions()
        {
            if ((int)Build.VERSION.SdkInt < 23)
            {
                return;
            }
            else
            {
                var permissions = new string[] { Manifest.Permission.ReadExternalStorage, Manifest.Permission.WriteExternalStorage, Manifest.Permission.Internet };
                RequestPermissions(permissions, 1);
            }
        }
```

**Comment by jfversluis** [comment]
Please have a look at https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows. This repo is no longer maintained and active development is ongoing there
