### ISSUE TITLE
This functionality is not implemented in the portable version of this assembly.

### ISSUE THREAD

**Issue by gjorgji88** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#41]
This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

This is what i get when trying to use it in iOS project. I confirm that references are properly added and iCloud drive is configured.

**Comment by S3ns3o** [comment]
Hello, Got the same issue, do you have any news about it?

**Comment by gjorgji88** [comment]
No, i just had to remove this component. I made a custom platform specific implementation in xamarin iOS.

**Comment by S3ns3o** [comment]
@gjorgji88 I find in the entitlements a configuration key that is 
<key>com.apple.developer.ubiquity-kvstore-identifier</key>
	<string>$(AppIdentifierPrefix)$(CFBundleIdentifier)</string>
Do you know if I must change that, or is it good?

**Comment by Jamarsoft** [comment]
Having the same issue with the nuget package.  Not working on IOS Simulator and gives me

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

Error

**Comment by GlenConway** [comment]
See #28

**Comment by CarlosJeJe** [comment]
Someone found the solution?

**Comment by navyseai** [comment]
Same problem... did you tried it in a physical device? maybe it just doesnt work in the simulator. I don't have a device to test right now.

**Comment by CarlosJeJe** [comment]
No navyseai, the same problem, some other alternative?

**Comment by kasra21** [comment]
You guys can use LeoJHarris.Plugin.FilePicker for now, but don't forget to setup your icloud (it s not perfect but does the job).

https://github.com/LeoJHarris/FilePicker

**Comment by jfversluis** [comment]
This should now be working in this NuGet: https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/1.4.0-beta

If not, please open a issue on the new repo where development will be continued: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues

**Comment by gonzalonm** [comment]
Try to rebuild all projects. It worked for me

**Comment by kosta59** [comment]
Moving up to compile 7.1 fixed the issue for me.
