### ISSUE TITLE
Pick multiple files

### ISSUE THREAD

**Issue by tuandunguit** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#42]
Hi, 
Can we pick multiple files at a time with this lib?

**Comment by jfversluis** [comment]
Not at once, no. Sorry!

**Comment by rafaelrmou** [comment]
Not yet, but we will provide this!

**Comment by kaushalyacs** [comment]
@rafaelrmou @jfversluis Do you support multiple files now?

**Comment by jfversluis** [comment]
Multiple files is nog supported yet. Also this repo is not maintained anymore. Please have a look at: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows
