### ISSUE TITLE
Could you make a new nuget package ?

### ISSUE THREAD

**Issue by MereDoku** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#45]
With the last nuget, there is a bug when cancel a picking file on Android.
But when I debug it with your code source this bug is corrected.
Could you make a new nuget package please ?

**Comment by procopio** [comment]
Please!

**Comment by jfversluis** [comment]
There is already an issue for this #22 but @rafaelrmou hasn't granted me the rights yet, or did it himself. I'm closing this one to prevent duplicate issues.
