### ISSUE TITLE
CrossFilePicker doesn't work on iOS

### ISSUE THREAD

**Issue by grammatn** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#49]
I tried to use CrossFilePicker PickFile function to choose file in my xamarin form but it doesn't work.

It said "This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

**Comment by ctrippel1** [comment]
It appears (to me) to be a NuGet package problem.  When I installed the package to the iOS project it located the FilePicker.dll in the 'portable...' folder.  This assembly uses a compiler directive in CrossFilePicker.cs to throw the message you are seeing (i.e. this portable assembly shouldn't be used for the native projects).  I believe the assembly in the MonoTouch10 folder is the correct assembly to be referenced.

**Comment by Greg767** [comment]
I confirm this. You must reference manually the DLLs from the MonoTouch10 folder and the plugin will work on iOS.

**Comment by ismailsameer12** [comment]
Hi Greeg767,
i was tried to add reference manually in xamarin iOS but NSInternalinconsistencyexception occur.
how to solve this?

**Comment by Greg767** [comment]
Sorry I have no idea about that problem. I never had that one before.

**Comment by ismailsameer12** [comment]
Hi Greg767,
Thanks for you response,its ok

**Comment by johankson** [comment]
For more information, on iOS I had to change the TakeMediaAsync() method to not re-read the file again. Don't know if it's worth to do a PR since the project seems to be badly managed at the moment?

```csharp 
Handler = (s, e) => {
var tcs = Interlocked.Exchange(ref _completionSource, null);

 Func<Stream> streamGetter = null;
if(e.FileByte != null)
{
    streamGetter = () => new MemoryStream(e.FileByte);
}
else
{
    streamGetter = () => File.OpenRead(e.FilePath);
}

tcs?.SetResult(new FileData(e.FilePath, e.FileName, streamGetter));
```

**Comment by jfversluis** [comment]
This should now be working in this NuGet: https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/1.4.0-beta

If not, please open a issue on the new repo where development will be continued: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues

**Comment by lohitha123** [comment]
Hi,

It is not working in ios.

if any one got success in ios..Please post your solution

**Comment by jfversluis** [comment]
@lohitha123 please see #87
