### ISSUE TITLE
Need example

### ISSUE THREAD

**Issue by Specko93** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#51]
Can someone give me an example of FilePicker, I don't know how to call it..

**Comment by procopio** [comment]
```
var filedata = await Plugin.FilePicker.CrossFilePicker.Current.PickFile();

                var myPickedFile= new MyPickedFile
                {
                    Name = filedata.FileName,
                    Content = filedata.DataArray,
                };
```

**Comment by nmano2188** [comment]
MyPickedFile what is that?

**Comment by procopio** [comment]
A simple class:

```
public class MyPickedFile
    {
        public string Name { get; set; }
        public byte[] Content { get; set; }
    }
```

**Comment by nmano2188** [comment]
How do i get File path of the selected file?

**Comment by procopio** [comment]
I don't get the file path, just file Name and the Content.
Load the Content on a Stream and use the file as you need.

**Comment by jfversluis** [comment]
There are samples available on the new repo on: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues
