### ISSUE TITLE
Picker dialog Not opened for Android in Xamarin.Forms.

### ISSUE THREAD

**Issue by SamuelCardo** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#57]
I implemented the picker dialog in Xamarin.Forms project.
When I opened it, it shows shows black screen and got stuck, no errors or warnings.
Can you please let me know what happened?

**Comment by fabri777** [comment]
I have the same problem as Samuel. Please help

**Comment by ddelamare** [comment]
Are you using "await"? When I remove that, then I get a black screen. You can try this:
`            FileData filedata = await CrossFilePicker.Current.PickFile();
`

**Comment by jfversluis** [comment]
This should now be working in this NuGet: https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/1.4.17-beta

If not, please open a issue on the new repo where development will be continued: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues
