### ISSUE TITLE
Could not find a part of the path

### ISSUE THREAD

**Issue by mayur2871** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#58]
@keannan5390 @jfversluis @tanure @jbravobr @leosoareslima 

i am getting exception while getting DataArray
Following is the my code for file picking it's working on android perfectly and throwing exception in iOS
Cold not find a part of the path "path of document"
            try
            {
                var filedata = await CrossFilePicker.Current.PickFile();
                lblFileName.Text = "FileName :-" + filedata.FileName +"\n"+ filedata.FilePath;
                lblFileData.Text = ""; 
                lblFileData.Text = filedata.DataArray.Length.ToString();
            }
            catch (Exception exception)
            {
                System.Diagnostics.Debug.WriteLine(exception);
                lblFileData.Text = "Exception::\n" + exception.Message;
                //throw;
            }

**Comment by nrb1238** [comment]
@mayur2871 , could found the solution for it?

**Comment by XnainA** [comment]
@mayur2871 , @nrb1238 could found any solution for it?

**Comment by XnainA** [comment]
@nrb1238  thank you so much for your time and efforts.
Solution for  FilePath: https://www.nuget.org/packages/pt.Xamarin.Plugin.FilePicker/
https://github.com/ArtjomP/FilePicker-Plugin-for-Xamarin-and-Windows

**Comment by jcus0006** [comment]
I have exactly the same issue but the branch does not seem to work for me. I get the following exception:

> {System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

Any idea why it does not work for me?

**Comment by jfversluis** [comment]
Please have a look at https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows. This repo is no longer maintained and active development is ongoing there
