### ISSUE TITLE
Empty filename under Android 7.0

### ISSUE THREAD

**Issue by RalphHerold** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#60]
Reproducable on a HUAWEI P10 Lite running under Android 7.0:

A file picked from local Download folder returns a FileData object with correct DataArray field but the filename member is empty

**Comment by jfversluis** [comment]
This should now be working in this NuGet: https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/1.4.17-beta

If not, please open a issue on the new repo where development will be continued: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues
