### ISSUE TITLE
FilePicker.FilePath does not exist in nuget package

### ISSUE THREAD

**Issue by yecicen** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#61]
`namespace Plugin.FilePicker.Abstractions
{
    public class FileData
    {
        public FileData();

        public byte[] DataArray { get; set; }
        public string FileName { get; set; }
    }
}`

it has only DataArray and FileName attributes, and I couldn't find a method to get filePath inside those.

**Comment by ismailsameer12** [comment]
Hi,
when using cross filepicker in xamarin iOS but system.NotImplemented exception occur,how to slove?

**Comment by jfversluis** [comment]
This should now be working in this NuGet: https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/1.4.0-beta

If not, please open a issue on the new repo where development will be continued: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues
