### ISSUE TITLE
update UIDocumentMenuViewController from to UIDocumentPickerViewController

### ISSUE THREAD

**Issue by coordenacaofidelitymobile** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#63]
Need update UIDocumentMenuViewController from to UIDocumentPickerViewController to support iOS 11+

**Comment by jfversluis** [comment]
This should now be working in this NuGet: https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/1.4.0-beta

If not, please open a issue on the new repo where development will be continued: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues
