### ISSUE TITLE
Need Example

### ISSUE THREAD

**Issue by nmano2188** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#65]
How to get File Path of the selected file?
 var data = await Plugin.FilePicker.CrossFilePicker.Current.PickFile();
            
            var fName = data.FileName;
            var Content = data.DataArray;

**Comment by cocoke** [comment]
```
FileData file = await CrossFilePicker.Current.PickFile();
string fName = Path.GetFileName(file.FileName);
```

**Comment by jfversluis** [comment]
Have a look at the sample project in the new repo https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows or open an issue if you still can't get it to work.

**Comment by manonaga2188** [comment]
@jfversluis  I want sample for iOS project. 
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows repo does not have iOS sample.

How to implement this in xamarin iOS
