### ISSUE TITLE
Unable to install on Xamarin.Mac

### ISSUE THREAD

**Issue by HobDev** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#69]
I try to install the package on pcl project, uwp client and mac client project. The error is 👎 
Could not install package 'Xam.Plugin.FilePicker 1.1.0'. You are trying to install this package into a project that targets 'Xamarin.Mac, Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. for more information, contact the package author

**Comment by jfversluis** [comment]
Did you target Mac OS 10.12+?

**Comment by jfversluis** [comment]
I've created a sample project on https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows

If you still can't get it to work, please open an issue there as development will be continued there.

**Comment by jerry2007** [comment]
I have same issue...

The problem is in nuget package... there is not support for xamarin.Mac20
If you reference the project directly it works...

Can you create new nuget package with Xamarin.Mac20 support pls?

**Comment by jfversluis** [comment]
Please check and submit on the new repo https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows

**Comment by jerry2007** [comment]
After install latest beta package it works... thnak you
