### ISSUE TITLE
Nothing happens on iOS

### ISSUE THREAD

**Issue by drasmith** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#70]
I have set this up to prompt to pick a file from an action sheet result. When the code calls CrossFilePicker.Current.PickFile(), nothing happens. It never returns from the awaiter. If I remove the entitelments.plist from the properties, I get the no entitlement found error so I know it is doing something. Just not displaying the popup. Any help would be appreciated. The same project works on Android.

**Comment by mingle75** [comment]
There is a known issue with iOS 11. See PR# 68 at https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/pull/68.

**Comment by jfversluis** [comment]
PR merged and moved over code to own repo to publish NuGet with this. Development will be continued there. NuGet beta with this code is here: https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/1.4.0-beta
