### ISSUE TITLE
Pick only specific file types

### ISSUE THREAD

**Issue by IeuanWalker** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#74]
Is there a way to limit the file types displayed?

**Comment by jfversluis** [comment]
In an effort to further develop this plugin I have moved it into my own account: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows

There is a PR and issue going around this subject: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues/24 please let's continue there.

**Comment by IeuanWalker** [comment]
@jfversluis great thanks

**Comment by IeuanWalker** [comment]
Closing as no I no longer use this package
