### ISSUE TITLE
File picker cancel causes error

### ISSUE THREAD

**Issue by IeuanWalker** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#75]
Xamarin.forms android
Plugin - v1.2.1

If the user cancels selecting a file it causes a null reference exception

Here is my code - 

```
try
{
        UserDialogs.Instance.ShowLoading("Loading");
        selectedFile = await CrossFilePicker.Current.PickFile();
}
catch (Exception ex)
{
        System.Diagnostics.Debug.WriteLine(ex);
}
finally
{
        UserDialogs.Instance.HideLoading();
}

if (selectedFile != null)
{
        // do stuff with file
}
// End of method where error is triggered
```

Here is the crash report from AppCentre

![image](https://user-images.githubusercontent.com/6544051/36235283-74ca2658-11e7-11e8-9005-68c6f8f265a9.png)

**Comment by jfversluis** [comment]
As mentioned in the before issue, development is discontinued here. Please open new issues on my account's repo.
