### ISSUE TITLE
FilePicker for Xamarin.Ios doesn't work

### ISSUE THREAD

**Issue by willowTank** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#76]
I am going to filename from iCloud in Xamarin.Ios by using FilePicker
But Actually it doesn't work
So when I select file, it return null or emptystring
How can i fix it? Please help me

**Comment by willowTank** [comment]
"This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."
I got over messages

**Comment by achayi** [comment]
In iOS project, remove the references for filepicker from NetStandard folder and add them from iOS10 folder or MonoTouch10 folder.

**Comment by jfversluis** [comment]
In an effort to further develop this plugin I have moved it into my own account: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows

Please move your questions or issues to there. This particular issue has been fixed in the newest beta packages.
