### ISSUE TITLE
File picker not working in iPad

### ISSUE THREAD

**Issue by MohanXamarin** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#78]
I'm using Xamarin.Plugin.FilePicker in MvvmCross."https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows" for the browser "var pickedFile = await CrossFilePicker.Current.PickFile();" getting null value from pickerfile.
it's working fine in iPhone but **not working in iPad.** can you please anyone suggest, what's the problem.
please share any other dll.

**Comment by jfversluis** [comment]
Please have a look and try https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows as this repo is no longer maintained
