### ISSUE TITLE
Pick File as Stream

### ISSUE THREAD

**Issue by mattleibow** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#8]
How hard will it be to pick / save a file as a `Stream` instead of a `byte[]`? This way, the entire data does not have to be loaded into memory.

**Comment by Pandalien** [comment]
Try this?
var fileDate = await Plugin.FilePicker.CrossFilePicker.Current.PickFile();
byte[] data = fileDate.DataArray;

**Comment by jfversluis** [comment]
@mattleibow I've implemented it in my fork since this seems abandoned, you can find it [here](https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows) there is a NuGet in preview with the `Stream` functionality

**Comment by jfversluis** [comment]
This should be implemented in the code now, will look at releasing a new NuGet soon!
