### ISSUE TITLE
Directory Browser to select a location for saving a file

### ISSUE THREAD

**Issue by bharatdwarkani** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#80]
It would be good if a feature is added to pick a directory location for saving a file. Similar to how a file is picked or if already possible then please provide suggestion on how to use it.

**Comment by jfversluis** [comment]
Please have a look at https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows and open an issue there. This repo is no longer maintained
