### ISSUE TITLE
[iOS] This functionality is not implemented in the portable version of this assembly

### ISSUE THREAD

**Issue by sky018** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#83]
Exception:
{System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation. at Plugin.FilePicker.CrossFilePicker.get_Current ()

Problem Description:

I made sure all the packages were installed for my main application project and for both iOS and Android. However it only occurs on iOS when trying to choose file from the drive. Are there any initialization to do in order for me to use the plugin for iOS? 

Plugin Version: 1.2.1
Upgrade to 1.4.0-beta (Same issue)

**Comment by jcus0006** [comment]
Updating to the latest Beta version: 2.0.81 should fix this problem.

**Comment by jfversluis** [comment]
Please have a look at https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows. This repo is no longer maintained and active development is ongoing there
