### ISSUE TITLE
System.NotImplementedException during xUnit test from Xam.Plugins.Settings

### ISSUE THREAD

**Issue by arichar1990** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#88]
I am getting the following error when I try to run an xUnit test in a Xamarin project that uses Xam.Plugins.Settings to store data to the device:

`Message: System.NotImplementedException : This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.`

The exception occurs in the ISettings property initialization of the Settings class, which has the following form:

```
public static class Settings
    {
        private static ISettings AppSettings
        {
            get
            {
                return CrossSettings.Current;
            }
        }
}
```
When xUnit gets to the return CrossSettings line, the error occurs. Any chance anyone can tell me why this is happening? I have the nuget package installed in both the iOS and Android projects.

**Comment by jfversluis** [comment]
Please see #87
