### ISSUE TITLE
.NETStandard.Version=2.0 support?

### ISSUE THREAD

**Issue by MihailsKuzmins** [Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows#89]
Currently the package supports .NETFramework, Version=4.6.1., so I am wondering will .NETStandard.Version=2.0 also be supported?
Thanks

**Comment by jfversluis** [comment]
Please see #87

**Comment by jfversluis** [comment]
Please see #87

**Comment by MihailsKuzmins** [comment]
@jfversluis Yes, sorry about the spam-issue. It was too late when I noticed your post.

**Comment by jfversluis** [comment]
No worries :)
